apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    name: port-http
    protocol: TCP
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000