
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  selector:
    app: ftps
  ports:
  - port: 21
    name: port-ftps
    protocol: TCP
    targetPort: 21
  - port: 10100
    name: port-passv
    protocol: TCP
    targetPort: 10100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 10100